# Custom transformation

based on Section 5.3.8 Custom transformers
https://scikit-learn.org/stable/modules/preprocessing.html

In [1]:
import numpy as np
from sklearn.preprocessing import FunctionTransformer

# Define a custom transformer with log as the forward transform and exp as the inverse

In [2]:
log_transformer = FunctionTransformer(np.log, np.exp, validate=True)

# create a test two dimensional array

In [3]:
X = np.array([[1, 2], [3, 4]])
X

array([[1, 2],
       [3, 4]])

# Transform the array into a logarithmic scale

In [4]:
X_t = log_transformer.transform(X)
X_t

array([[0.        , 0.69314718],
       [1.09861229, 1.38629436]])

# Do the inverse of the transformation to return to a linear scale

In [5]:
X_inv_t = log_transformer.inverse_transform(X_t)
X_inv_t

array([[1., 2.],
       [3., 4.]])